spring.application.name=BE-DATN
spring.mongodb.uri=mongodb://tuandang2411:tuandang2411%40@localhost:27017/estateadvance?authSource=admin

app.seed-buildings=false

server.tomcat.max-http-form-content-size=50MB
server.tomcat.max-swallow-size=50MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.servlet.session.persistent=false
server.tomcat.persist-session=false
file.upload-dir=uploads/legal-documents

spring.ai.google.genai.api-key=${GEMINI_API_KEY:AIzaSyDFVdLzFgOvcfTuCj_wTkCE8lGNzjRJF68}

spring.ai.google.genai.chat.options.model=${GEMINI_MODEL:gemini-2.5-flash}
